### ISSUE TITLE
E2E Test Case recording so that any one can go through that recording any see where it is failed.

### ISSUE THREAD

**Issue by jayeshd7** [WasiqB/coteafs-selenium#107]
**Is your feature request related to a problem? Please describe.**

We are trying to implement recording option with screen shot.
so that when TC run on any CI  server like Jenkins , circleCI or team city they can attach video as well.

**Describe the solution you'd like**
I am able to record the screen where on CI monitor is present means without head less browser.
unable to find any solution where we can record headless browser stuff.

**Describe alternatives you've considered**

**Additional context**

**Comment by jayeshd7** [comment]
package com.viu.utils;

import org.monte.media.Format;
import org.monte.media.FormatKeys.MediaType;
import org.monte.media.Registry;
import org.monte.media.math.Rational;
import org.monte.screenrecorder.ScreenRecorder;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

import static org.monte.media.AudioFormatKeys.EncodingKey;
import static org.monte.media.AudioFormatKeys.FrameRateKey;
import static org.monte.media.AudioFormatKeys.KeyFrameIntervalKey;
import static org.monte.media.AudioFormatKeys.MIME_AVI;
import static org.monte.media.AudioFormatKeys.MediaTypeKey;
import static org.monte.media.AudioFormatKeys.MimeTypeKey;
import static org.monte.media.VideoFormatKeys.*;

/**
 * @Author -Jayesh Dalal
 * <p>
 * Media recording library.
 */


public class ScreenRecorderUtil extends ScreenRecorder {
    public static ScreenRecorder screenRecorder;
    public String name;

    public ScreenRecorderUtil(GraphicsConfiguration cfg, Rectangle captureArea, Format fileFormat,
                              Format screenFormat, Format mouseFormat, Format audioFormat, File movieFolder, String name)
            throws IOException, AWTException {
        super(cfg, captureArea, fileFormat, screenFormat, mouseFormat, audioFormat, movieFolder);
        this.name = name;
    }

    @Override
    protected File createMovieFile(Format fileFormat) throws IOException {

        if (!movieFolder.exists()) {
            movieFolder.mkdirs();
        } else if (!movieFolder.isDirectory()) {
            throw new IOException("\"" + movieFolder + "\" is not a directory.");
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH.mm.ss");
        return new File(movieFolder,
                name + "-" + dateFormat.format(new Date()) + "." + Registry.getInstance().getExtension(fileFormat));
    }

    public static void startRecord(String methodName, int width, int height) throws IOException, AWTException {
        File file = new File("./target/recordings");



        Rectangle captureSize = new Rectangle(0, 0, width, height);


        GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().
                getDefaultScreenDevice()
                .getDefaultConfiguration();
        screenRecorder = new ScreenRecorderUtil(gc, captureSize,
                new Format(MediaTypeKey, MediaType.FILE, MimeTypeKey, MIME_AVI),
                new Format(MediaTypeKey, MediaType.VIDEO, EncodingKey, ENCODING_AVI_TECHSMITH_SCREEN_CAPTURE,
                        CompressorNameKey, ENCODING_AVI_TECHSMITH_SCREEN_CAPTURE, DepthKey, 24, FrameRateKey,
                        Rational.valueOf(15), QualityKey, 1.0f, KeyFrameIntervalKey, 15 * 60),
                new Format(MediaTypeKey, MediaType.VIDEO, EncodingKey, "black", FrameRateKey, Rational.valueOf(30)),
                null, file, methodName);
        screenRecorder.start();
    }

    public static void startRecord(String methodName) throws Exception {
        try {


            startRecord(methodName, 1920, 1080);
        } catch (Exception es) {

        }
    }

    public static void stopRecord() throws Exception {
        screenRecorder.stop();
    }
}




-----
Dependency which i am using 


<dependency>
            <groupId>com.automation-remarks</groupId>
            <artifactId>video-recorder-core</artifactId>
            <version>2.0</version>
        </dependency>


@WasiqB I am trying with toolkit option , but it will work when CI machine has monitor.
so I used above code.
Even i tried hard code parameter (width & height) but unable to record screen on headless browser.


@mfaisalkhatri @WasiqB  any option which we can try , in this framework.
I already attach a code & dependency which you can use for further enhancement.

**Comment by WasiqB** [comment]
@jayeshd7 , great analysis. I'll try other options which should work for both headless and non headless mode.

Earlier I had raised similar issue #16 . I'll close that and we can keep this ticket.

**Comment by jayeshd7** [comment]
@WasiqB  whenever you are trying other options please let me know , so that i can also learn .
how and which approach you decided .
