### ISSUE TITLE
Attach screen shot on any step

### ISSUE THREAD

**Issue by MonoAutomation** [WasiqB/coteafs-selenium#120]
Hello, 
It's my request, can you add attaching screen shot wherever user wants to attach on any case...

**Comment by WasiqB** [comment]
You can use `page.onDriver().saveScreenshot();`, this will return screen shot file object, which you can use to attach to any report.

**Note:**
`page` can be any page object instance.

E.g.:

```java
Login page page = new LoginPage();
File screenshot = page.onDriver(). saveScreenshot();
```

**Comment by MonoAutomation** [comment]
Thank you for quick update, till I within the framework I can follow the same but suppose if I want use somewhere else like extent reports, I want to take screenshot ..in this case really am not thinking how I can use it...

which is completely separate class....< package:MyReports/class:extentreport>
 @Override
    public void onTestFailure(ITestResult iTestResult) {
....hear the stuff will come  to take screen shot and attach it..
    }

may be am not having enough knowledge to undressing your wonderful framework...still requesting ...please help in this
