### ISSUE TITLE
Generic return method is required in "ElementKey" interface as currently it supports for only String return types.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-selenium#133]
Generic return method is required in "ElementKey" interface.
As far as test data is concerned there might be multiple range of values which user would require to return like int, boolean, double, String, etc.
As of now we have support for String only, so its difficult for the user to cast values in another data type and there is lot of workaround required for this.
We need to change the retrun method to Generic to ease its use.

**Comment by WasiqB** [comment]
It's already handled. The input value when passed to `addInputValue` method can be of any type. The same type will get returned in `value` method.
