### ISSUE TITLE
BrowserPage class is required

### ISSUE THREAD

**Issue by WasiqB** [WasiqB/coteafs-selenium#2]
This class is responsible for the following:
* It will allow browser specific actions like:
  * Navigate to
  * Forward
  * Back
  * Refresh
  * Title
  * Screenshot
  * Switch to
  * Open windows
  * Alerts
* It will allow to interact with a specific element with actions like:
  * Click
  * Double click
  * Right click
  * Enter text
  * Append text
  * Clear
  * Hover
  * Drag and drop
  * Check and Uncheck
  * Send key events
  * Attribute value
* It should allow inline element verifications like:
  * Equals to
  * Not equals to
  * Contains
  * Does not contains
  * Is empty
  * Is not empty
  * Starts with
  * Ends with
  * Is visible
  * Is enabled
  * Is hidden
  * Is missing
  * Is disabled
  * Is selected
  * Is focused

**Comment by mfaisalkhatri** [comment]
Updated File..
[Framework_Method_Names.xlsx](https://github.com/WasiqB/coteafs-selenium/files/1955299/Framework_Method_Names.xlsx)
