### ISSUE TITLE
Require Support for IE Browser.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-selenium#30]
Framework should support executing tests in IE and Edge Browsers.

**Comment by mfaisalkhatri** [comment]
Check this link which shows how to run tests on edge browser:
https://www.softwaretestingmaterial.com/launch-edge-browser-using-microsoft-webdriver/

**Comment by WasiqB** [comment]
Ticket scope reduced to only IE.

**Comment by WasiqB** [comment]
Changes merged.
