### ISSUE TITLE
Need to update the selenium tests so that it can be run in all supported browsers.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-selenium#38]
Selenium tests needs to be updated so that it can be run in all supported browsers.
Currently, the website "Guru99 bank Project" used for running tests has support for Chrome browser only, hence the tests are not successful in Firefox and IE browsers.
Selenium tests will now be conducted on "Saucedemo.com" which supports Chrome,IE as well as Firefox browsers.

**Comment by mfaisalkhatri** [comment]
As discussed, we would be using automationpractice.com website for running tests.

**Comment by WasiqB** [comment]
@mfaisalkhatri , any progress on this?

**Comment by mfaisalkhatri** [comment]
@WasiqB working on this, will be done by next week.

**Comment by WasiqB** [comment]
@mfaisalkhatri , write tests using new page factory model, this will also help test that feature as well.

**Comment by mfaisalkhatri** [comment]
Need to check whether this is working fine as unit tests are updated in #8  and also we have changed the test website.
