### ISSUE TITLE
WebDriver manager Configuration.

### ISSUE THREAD

**Issue by jayeshd7** [WasiqB/coteafs-selenium#41]
Instend of putting all Webdriver like chrome driver ,gecko driver into drivers folders with respect to OS.
we can get the OS First then based on that we can use webdriverManaged dependency in pom.xml
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>3.4.0</version>
    <scope>test</scope>
</dependency>

and use it via 
WebDriverManager.chromedriver().setup();
WebDriverManager.firefoxdriver().setup();

**Comment by WasiqB** [comment]
Changes merged to develop.
