### ISSUE TITLE
When PageFactory.init is removed from a particular class, Framework automatically switches to the base class where init is called.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-selenium#59]
When PageFactory.init is removed from a particular page, Framework automatically switches to the first Page where init is called.

Steps:
01. Create a Page object for MainPage of Website and call PageFactory.init in this class.
02, Create another Page Object for SignOut and do not call PageFactory.init in this class.

Acceptance Criteria:
Proper error/exception should be thrown in this case and framework should not switch to base class where init method is called.

**Comment by WasiqB** [comment]
This ticket no longer required as Page factory is now scrapped.
