### ISSUE TITLE
Error Message on assertion: The method verifyDisplayed() from the type IVerifyElement refers to the missing type BooleanSubject

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-selenium#60]
Following error message is displayed when user tries to assert on element object:
**The method verifyDisplayed() from the type IVerifyElement refers to the missing type BooleanSubject**

Steps:
01. Create a class for page object and locate element for signIn link.
02. Try to use signIn().verifyIsDisplayed().isTrue() in actions class.

Currently, user is not allowed to use assertion and above error message is displayed.

Acceptance Criteria:
User should be allowed to use assertion successfully without any error.

**Comment by WasiqB** [comment]
@mfaisalkhatri , is this issue still exists?

**Comment by mfaisalkhatri** [comment]
@WasiqB will check and revert, pls keep this open for sometime.

**Comment by mfaisalkhatri** [comment]
Verified, this is working fine, hence, closing the ticket.
