### ISSUE TITLE
Missing annotations for Functional interfaces.

### ISSUE THREAD

**Issue by revdfdev** [WasiqB/coteafs-selenium#73]
IScriptAction and IScreenAction are functional interfaces and should be declared as Functional interfaces as with java8-api

**Comment by revdfdev** [comment]
Let me do it please.

**Comment by WasiqB** [comment]
@revdfdev , as discussed this ticket is no longer required as it is designed for abstraction.

In the meantime, you can look into #22 or #13 , but #22 is highest in priority.
