### ISSUE TITLE
how to setup "Parallel execution of tests on different browsers" using this framework?

### ISSUE THREAD

**Issue by KamalnathanAnbazhagan** [WasiqB/coteafs-selenium#76]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
 ##@WasiqB

**Comment by WasiqB** [comment]
@KamalnathanAnbazhagan , you can configure your `testng.xml` to run tests parallelly. Also you can have a look at this sample [`testng.xml`](https://github.com/WasiqB/coteafs-selenium/blob/master/testng-all-browsers.xml) file to see how you can configure your suite to run on multiple browsers.

Hope this answers your question.

**Comment by WasiqB** [comment]
Closing since no further activity on this issue.
