### ISSUE TITLE
Driver manager settings required.

### ISSUE THREAD

**Issue by WasiqB** [WasiqB/coteafs-selenium#93]
**Is your feature request related to a problem? Please describe.**

Currently there is no control for the user on WebDriverManager on how and where it should download the driver exe.

**Describe the solution you'd like**

It is required to allow user the control on WebDriverManager, like:

- [x] Download path
- [x] Version of Driver
- [x] Force cache
- [x] Force download
- [x] Driver exe URL
- [ ] Proxy settings (Will be done on demand).

More settings can be handled later if requested.

**Comment by jayeshd7** [comment]
Hi Wasiq sir,
Below is the point which webdriver manager maintained 


    It checks the version of the browser installed in your machine (e.g. Chrome, Firefox).
    It checks the version of the driver (e.g. chromedriver, geckodriver). If unknown, it uses the latest version of the driver.
    It downloads the WebDriver binary if it is not present on the WebDriverManager cache (~/.m2/repository/webdriver by default).
    It exports the proper WebDriver Java environment variables required by Selenium (not done when using WebDriverManager from the CLI or as a Server).



Regarding Proxy --
WebDriverManager.chromedriver()
                 .version("2.40")
                 .arch32()
                 .proxy("myproxyhostname:80")
                 .proxyUser("myusername")
                 .proxyPass("myawesomePassword")
.setup();

we can use that.

**Comment by jayeshd7** [comment]
https://github.com/bonigarcia/webdrivermanager

**Comment by WasiqB** [comment]
@jayeshd7 , yes I saw that. That's where I got the idea in first place. Would you like to work on it?
